from typing import List


RSS_SOURCES: List[str] = ["https://rsshub.app/dgtle/whale/category/0",
    "https://www.zhihu.com/rss",
    "https://36kr.com/feed",
    "https://www.freebuf.com/feed",
    "https://talk.swift.gg/static/rss.xml",
    "https://sspai.com/feed",
    "https://www.huxiu.com/rss/0.xml",
    "https://www.pingwest.com/feed/all",
    "https://www.pingwest.com/feed/",
    "https://rsshub.app/rsshub/rss",
    "http://www.dgtle.com/rss/dgtle.xml",
    "https://www.oschina.net/blog/rss",
    "https://dq.yam.com/rss.php",
    "https://feed.iplaysoft.com/",
    "http://jandan.net/feed",
    "https://news.un.org/feed/subscribe/zh/news/all/rss.",
    "http://www.ftchinese.com/rss/news",
    "https://rss.cnbeta.com/",
    "http://www.rologo.com/feed",
    "https://www.qiushibaike.com/hot/rss",
    "https://www.yymiao.cn/feed",
    "https://www.photoworld.com.cn/feed",
    "http://www.alibuybuy.com/feed",
    "https://www.lieyunwang.com/newrss/feed.xml",
    "http://app.iheima.com/?app=rss",
    "https://juejin.im/rss",
    "https://xueqiu.com/hots/topic/rss",
    "http://www.chanpin100.com/feed",
    "https://buzzorange.com/feed/",
    "http://www.woshipm.com/feed",
    "https://www.meihua.info/feed",
    "https://www.tmtpost.com/rss",
    "https://www.aqniu.com/feed",
    "https://www.yunyingpai.com/feed",
    "https://www.shuge.org/feed",
    "http://zhainanba.net/feed",
    "http://www.qdaily.com/feed.xml",
    "https://songshuhui.net/feed",
    "http://research.sinica.edu.tw/feed/"]