"""create table

Revision ID: a965d87dc35a
Revises: 
Create Date: 2020-02-27 16:22:35.570721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a965d87dc35a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bao_file',
    sa.Column('file_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件hash值'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('file_type', sa.String(length=32), nullable=True, comment='文件类型'),
    sa.Column('file_is_delete', sa.SMALLINT(), nullable=True, comment='删除状态 0 未删除 1 删除'),
    sa.Column('file_create_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('bao_file_user',
    sa.Column('file_user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False, comment='文件id'),
    sa.Column('add_time', sa.String(length=10), nullable=True, comment='添加时间'),
    sa.Column('file_user_state', sa.SMALLINT(), nullable=True, comment='1 创建(未验证) 2 有效 3 失效 4 删除'),
    sa.PrimaryKeyConstraint('file_user_id')
    )
    op.create_table('bao_login_record',
    sa.Column('record_id', sa.INTEGER(), nullable=False, comment='用户的登录记录'),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('op_time', sa.String(length=20), nullable=True),
    sa.Column('op_ip', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('bao_rss',
    sa.Column('rss_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rss_link', sa.String(length=255), nullable=True),
    sa.Column('rss_subtitle', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.String(length=20), nullable=True),
    sa.Column('rss_version', sa.String(length=10), nullable=True),
    sa.Column('rss_title', sa.String(length=255), nullable=True, comment='订阅的标题'),
    sa.Column('rss_state', sa.SMALLINT(), nullable=True, comment='# 1 创建(未验证) 2 有效 3 失效'),
    sa.PrimaryKeyConstraint('rss_id')
    )
    op.create_table('bao_rss_content',
    sa.Column('content_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rss_id', sa.INTEGER(), nullable=True, comment='属于哪一个订阅的内容'),
    sa.Column('content_link', sa.String(length=255), nullable=True),
    sa.Column('content_title', sa.String(length=255), nullable=True),
    sa.Column('content_image_cover', sa.String(length=255), nullable=True),
    sa.Column('published_time', sa.String(length=64), nullable=True),
    sa.Column('add_time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('bao_rss_content_collect',
    sa.Column('collect_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content_id', sa.INTEGER(), nullable=True),
    sa.Column('collect_time', sa.String(length=11), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=True, comment='1 收藏 0 删除 未收藏'),
    sa.PrimaryKeyConstraint('collect_id')
    )
    op.create_table('bao_rss_read_record',
    sa.Column('read_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('read_url_id', sa.INTEGER(), nullable=False),
    sa.Column('read_user_id', sa.INTEGER(), nullable=True),
    sa.Column('read_time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('read_id')
    )
    op.create_table('bao_rss_user',
    sa.Column('rss_user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rss_id', sa.INTEGER(), nullable=False),
    sa.Column('add_time', sa.String(length=20), nullable=True),
    sa.Column('rss_user_state', sa.SMALLINT(), nullable=True, comment='# 1 创建(未验证) 2 有效 3 失效'),
    sa.PrimaryKeyConstraint('rss_user_id')
    )
    op.create_table('bao_todo',
    sa.Column('todo_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('todo_title', sa.String(length=255), nullable=True, comment='待办标题'),
    sa.Column('add_time', sa.String(length=20), nullable=True, comment='添加时间'),
    sa.Column('bind_user_id', sa.INTEGER(), nullable=True, comment='绑定用户id'),
    sa.Column('todo_state', sa.SMALLINT(), nullable=True, comment=' # 1 创建 2 完成 3 删除'),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_table('bao_user',
    sa.Column('id', sa.INTEGER(), nullable=False, comment='用户的id'),
    sa.Column('sex', sa.SMALLINT(), nullable=True, comment='0 未设置 1 男性 2 女性'),
    sa.Column('identifier', sa.String(length=128), nullable=True, comment='用户的标识符，在某些情况不适合用id，会用此字段'),
    sa.Column('mobilephone', sa.String(length=11), nullable=True),
    sa.Column('nickname', sa.String(length=18), nullable=True, comment='用户昵称'),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True, comment='0 未激活 1 正常 2 异常 3 注销'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog_article',
    sa.Column('article_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False, comment='用户id'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('create_time', sa.String(length=10), nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True, comment='删除状态'),
    sa.Column('is_publish', sa.BOOLEAN(), nullable=True, comment='是否发布'),
    sa.PrimaryKeyConstraint('article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_article')
    op.drop_table('bao_user')
    op.drop_table('bao_todo')
    op.drop_table('bao_rss_user')
    op.drop_table('bao_rss_read_record')
    op.drop_table('bao_rss_content_collect')
    op.drop_table('bao_rss_content')
    op.drop_table('bao_rss')
    op.drop_table('bao_login_record')
    op.drop_table('bao_file_user')
    op.drop_table('bao_file')
    # ### end Alembic commands ###
