"""empty message

Revision ID: b05d82e6eb32
Revises: 1598c3d68251
Create Date: 2020-03-15 15:18:23.058691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b05d82e6eb32'
down_revision = '1598c3d68251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_article',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='用户id'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False, comment='文章内容'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='文章标题'),
    sa.Column('create_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='删除状态'),
    sa.Column('is_publish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否发布'),
    sa.PrimaryKeyConstraint('article_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
